### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by leoheck** [AsahiLinux/artwork#3]
What happened with this project? I did not see any other commit or anything else in the internet about it.

**Comment by marcan** [comment]
This is the *artwork repository*, so no, we aren't actively developing our logos...

**Comment by leoheck** [comment]
Yeah, sorry, it was posted in the wrong repo by mistake. I am trying to check exists a working linux for M1. I am done with shitty computers anymore. But it seems that any possible linux that will run on Apple Silicon is a bit far from being reality. How is the progress of making GPU working?

**Comment by marcan** [comment]
We're working on it. Please do not open issues to ask for progress reports; we post those on http://asahilinux.org/blog.

**Comment by leoheck** [comment]
Sure. This one is closed already. I could not find any news from this year. Are you thinking to release a post soon?
